### ISSUE TITLE
Saving bellhop output file

### ISSUE THREAD

**Issue by yor-b** [org-arl/arlpy#104]
I have to use some program which requires the bellhop output arrivals file as an input for some further processing. Is there some function to save these outputs to a file?

**Comment by mchitre** [comment]
Yes. Set debug to True and it will not delete the files until you have had a chance to explore them.

**Comment by yor-b** [comment]
Okay to answer my own question, I found these files when I actually ran this from a terminal. But it does not work correctly for vscode. Is there any way to save these files to a specific directory?
