### ISSUE TITLE
Output Unit of pm.compute_transmission_loss: dB or Conversion Needed?

### ISSUE THREAD

**Issue by riskaaudinaa** [org-arl/arlpy#105]
Hello, everyone. I have a question: I would like to calculate SNR in dB. I need to use transmission loss for this. I'm using ARLpy with Bellhop to model underwater communication, but I'm unsure about the output unit of transmission loss.

What is the output unit of `pm.compute_transmission_loss`? Is it already in dB, or do we need to convert it?

Thank you

**Comment by mchitre** [comment]
As the documentation clearly states, returns complex transmission loss at each receiver depth and range. To convert to dB, you would take 20 log abs of that.

**Comment by riskaaudinaa** [comment]
ah complex number,  i see . thank you so much
