### ISSUE TITLE
Incorrect amplitude showing in plot_arrivals()

### ISSUE THREAD

**Issue by rigelifland** [org-arl/arlpy#15]
The amplitude is calculated: `y = np.abs(arrival_amplitude)`, but abs takes the magnitude of the complex arrival_amplitude. It should only be using the real part of the amplitude as the complex portion discribes the phase: `y = np.abs(np.real(arrival_amplitude))`

**Comment by mchitre** [comment]
I'm not sure I understand what you mean. The magnitude of the complex number is the amplitude, and the angle of the complex number is the phase. So `np.abs(arrival_amplitude)` should be giving you the correct magnitude.

**Comment by rigelifland** [comment]
Yes, of course. I got embarassingly confused about this.

**Comment by mchitre** [comment]
No worries, thanks!
