### ISSUE TITLE
MS windows execution of bellhop notebook

### ISSUE THREAD

**Issue by tfabbri** [org-arl/arlpy#21]
Hello, 

I'm trying to use arlpy as interface for the Acoustic Toolbox. 

I've installed arlpy on a python 3.6 environment using Anaconda on a Windows 7 system. 
At the moment when I run `pm.models()` I obtain Fotran errors like the following:

```
In [2]: pm.models()
At line 39 of file ReadEnvironment.f90 (unit = 5, file = 'C:\Users\~~~~\AppData\Local\Temp\tmpl45gufmo.env')
Fortran runtime error: End of file

Error termination. Backtrace:

Could not print backtrace: libbacktrace could not find executable to open
#0  0xffffffff
#1  0xffffffff
#2  0xffffffff
#3  0xffffffff
#4  0xffffffff
#5  0xffffffff
#6  0xffffffff
#7  0xffffffff
#8  0xffffffff
#9  0xffffffff
#10  0xffffffff
#11  0xffffffff
#12  0xffffffff
#13  0xffffffff

Out[2]: ['bellhop']
```

Then if I run the command `rays = pm.compute_eigenrays(env)` seems working fine. 
Any suggestion? 
After going through the open issues, maybe this is related to #9

**Comment by mchitre** [comment]
Yes, quite likely. There have been a couple of changes in the latest Bellhop version, and I haven't had a chance to test it and make updates. I aim to get this done over the next couple of weeks. In the mean time, if you're able to test if the issue persists with a previous version of Bellhop (another user used [this](https://pulsar.byu.edu/dfvankom/acoustics-toolbox) as a workaround issue #18), that would be useful input for me.

**Comment by mchitre** [comment]
Should be the same as #18, and is now hopefully fixed.
