### ISSUE TITLE
Problem with Bellhop version

### ISSUE THREAD

**Issue by cristiantesconi1994** [org-arl/arlpy#23]
Hi,
I'm testing the software, but i have some problem. The problem i am exposing now has already been treated in issue #21: i tried to use the latest version of bellhop (bellhop.exe) and i obtain the sequent error: 
![first_problem](https://user-images.githubusercontent.com/32714103/54232282-913a0900-450a-11e9-94fd-7e3981cd7157.png), but plotray and eigenray work better.
So i tried to use previus version of bellop and the error described above no longer occurs, but plot_ray and eigenray don't work, obtaining the following error: 
![second_problem](https://user-images.githubusercontent.com/32714103/54232675-80d65e00-450b-11e9-9dd1-24145432d88e.png).
Can you give me any suggestion? how can i proceed?

Thanks very much in advance.

**Comment by mchitre** [comment]
I'm surprised there is a problem with older version of `bellhop` and plotting rays, since many regularly use that. Anyway, its time that `arlpy` moved to the latest `bellhop` and so I'll get that done as soon as possible.

**Comment by cristiantesconi1994** [comment]
I downloaded Bellop from http://oalib.hlsresearch.com/AcousticsToolbox/  and i copied the Bellhop.exe in the directory where i have my python script. Firstly i downloaded from the usual link above the Bellhop version in: 
![bellhop_1 png](https://user-images.githubusercontent.com/32714103/54265519-c891cf80-4575-11e9-8b44-de2d11b1983d.jpg)
and then i tried to use bellhop version in:
![bellhop_2 png](https://user-images.githubusercontent.com/32714103/54265582-f24af680-4575-11e9-82d0-159f8343da2e.jpg)
Have i tried correct version?
if not, could you attach bellhop.exe to put in the directory where I have my python script?

Thanks in advance.

**Comment by mchitre** [comment]
The latest `dev` should have fixed the issue with the latest `bellhop.exe` version. This will be part of the upcoming release.
