### ISSUE TITLE
Autonomous_driving_application_Car_detection using yolo 

### ISSUE THREAD

**Issue by sahusarkar** [org-arl/arlpy#46]

**Comment by sahusarkar** [comment]
class_names = read_classes("coco_classes.txt")
anchors = read_anchors("yolo_anchors.txt")
image_shape = (720., 1280.) 
![Screenshot (989)](https://user-images.githubusercontent.com/46740799/83343694-6e686000-a31b-11ea-84c1-428c664bfa43.png)

**Comment by mchitre** [comment]
I don't see anything to do with arlpy here.
