### ISSUE TITLE
Error with pm.models()

### ISSUE THREAD

**Issue by John-Ragland** [org-arl/arlpy#49]
Hi,

I've just installed Bellhop and am trying to run the notebook https://arlpy.readthedocs.io/en/latest/_static/bellhop.html to verify functionality.

I have compiled bellhop using gfortran, and have added Bellhop.exe to the PATH (trying both copying and pasting the file to the working directory and by using below sequece)
`import sys
sys.path.append(bellhop_dir)`

When I run `pm.models()`, the output is an empty list. I'm not sure what the issue is.

Thanks for the help!

**Comment by John-Ragland** [comment]
Actually, the output is an empty list. My bad.

**Comment by mchitre** [comment]
Getting an empty list means that arlpy didn't find bellhop.exe. Just try running bellhop.exe manually on the command line where you run Python from, and see if it finds it.

**Comment by John-Ragland** [comment]
It looks like I confused the $PATH with the python path. I added the path to bellhop.exe to $PATH and now I get the correct list: ['bellhop'].

Thanks!

**Comment by mchitre** [comment]
Great! Good luck with your modeling!!
