### ISSUE TITLE
one question about _select_model

### ISSUE THREAD

**Issue by haozhao10** [org-arl/arlpy#58]
File "../uwapm.py", line 570, in _select_model
    raise ValueError('No suitable propagation model available')
ValueError: No suitable propagation model available

**Comment by mchitre** [comment]
You need bellhop installed on your system for it to be available in arlpy

**Comment by haozhao10** [comment]
Thanks a lot. I have fixed this problem.

**Comment by gu5b4g** [comment]
> Thanks a lot. I have fixed this problem.

Hey, I know this is an old thread - so a long shot; but how did you go about fixing this problem? 
I used the GFortran compiler on my Mac - and am getting the same issue when I follow along on https://arlpy.readthedocs.io/en/latest/_static/bellhop.html
I am thinking it is to do with Bellhop being an exe and me attempting to run it on a Mac; but just incase its a simple fix before I go using parallels, I'd really appreciate any hints.
Thanks in advance!

**Comment by mchitre** [comment]
I do run Bellhop on a Mac. To do so, you need to install GFortran with the right versions of the libraries and then compile Bellhop.
