### ISSUE TITLE
Error when saving .png from bokeh interface

### ISSUE THREAD

**Issue by John-Ragland** [org-arl/arlpy#62]
When I select the save button a ray plot (below)
![image](https://user-images.githubusercontent.com/61983945/111093558-7bdf8700-84f6-11eb-9c9a-966df0fc0f98.png)

I get the following .png, which is the top left of the image that I want.
![image](https://user-images.githubusercontent.com/61983945/111093625-a6314480-84f6-11eb-9734-42b150e3e4a0.png)

Additionally is there a way that I can save an image in a custom file format (such as .eps)?

**Comment by mchitre** [comment]
I am unable to reproduce your problem, as the file saves fine for me. I'm guessing this is some incompatibility with the Bokeh library and your setup. Could you try using Bokeh directly for plots and see if those save fine?

I personally tend to use a screen capture to save the plot, rather than the Bokeh save option. That allows me to save in any format I want too.

**Comment by John-Ragland** [comment]
I get the same error when just using Bokeh, so it looks like this is a bug with Bokeh.

As for saving a plot, I would like to programmatically create figures for a publication that are vectorized. Is there any support for programmatically saving the figures? (such as the equivalent to matplotlib's matplotlib.pyplot.savefig())?

**Comment by John-Ragland** [comment]
I'm not sure how I could use the bokeh support for vectorized images within arlpy.

Thanks for the help!

**Comment by mchitre** [comment]
Yes, you can programmatically save the figure. See Bokeh link I posted above.

**Comment by John-Ragland** [comment]
I'm unsure how to get arlpy.plot.gcf() to work. This is what I'm trying right now
after creating an environment variable (env):

```
import arlpy.uwapm as pm

rays = pm.compute_eigenrays(env)
pm.plot_rays(rays, env=env, width=700)
fig = arlpy.plot.gcf()
```

arlpy.plot.gcf() returns None

**Comment by mchitre** [comment]
You'll need to hold the plot to get the handle.

Try this:
```
import arlpy.uwapm as pm
import arlpy.plot as plt

rays = pm.compute_eigenrays(pm.create_env2d())

plt.hold(True)
pm.plot_rays(rays, env=pm.create_env2d(), width=700)
fig = plt.gcf()
plt.hold(False)
```

**Comment by John-Ragland** [comment]
This fixed it for me thanks!
