### ISSUE TITLE
How do you make bellhop.exe available on the PATH

### ISSUE THREAD

**Issue by ZoeH95** [org-arl/arlpy#67]
I am a newbie at python but wanting to use acoustic modelling for my masters project, but needing some help in the set up if possible.

**Comment by mchitre** [comment]
1. Install Bellhop from http://oalib.hlsresearch.com/AcousticsToolbox/
2. If you're using Windows, you can follow [this](https://www.computerhope.com/issues/ch000549.htm) to set your PATH to point to wherever you install Bellhop. If you're using Linux/MacOS, you can follow [this](https://opensource.com/article/17/6/set-path-linux) instead.

Good luck!
