### ISSUE TITLE
How can I make sure that BELLHOP installed on my PC?

### ISSUE THREAD

**Issue by catauggie** [org-arl/arlpy#74]
Hi, I am user of windows 10 OS. 

I have installed BELLHOP from Acoustics Toolbox
http://oalib.hlsresearch.com/AcousticsToolbox/
But I don't understand how can I make sure that BELLHOP installed on my PC, because when I compile code in Jupyter I have an error No suitable propagation available

**Comment by mchitre** [comment]
You need to make sure that the `bellhop.exe` is in your `PATH`, so that you can run it on the command line before you run Jupyter.

**Comment by catauggie** [comment]
Can I clarify: what is the PATH?

**Comment by catauggie** [comment]
And what should I type in command line before run jupiter?

**Comment by mchitre** [comment]
https://www.maketecheasier.com/what-is-the-windows-path/

**Comment by catauggie** [comment]
so, I decided to install it again.
As I understood,
1)  I should download atWin10_2020_11_4.zip Binaries (zip file) for Windows 10 from http://oalib.hlsresearch.com/AcousticsToolbox/, right?
2) I found bellhop.exe (my folder \acoustic toolbox\atWin10_2020_11_4\atWin10_2020_11_4\windows-bin-20201102)
3) I have created PATH variable with mentioned above path
and finally the same error((

**Comment by catauggie** [comment]
I  don't understand how PATH can help to avoid this error. Maybe there are some extra options to fix?

**Comment by mchitre** [comment]
The `PATH` tells your computer where to find the executable for a command you're trying to run.

If you open a command prompt and type `bellhop.exe`, what do you see as output? If your `PATH` is correctly setup, it should be able to find `bellhop.exe` and run it and show you the output. If not, it'll tell you that it was not found.

If you're successfully able to run it, then running Jupyter from the same command prompt should allow `arlpy` to find `bellhop.exe` too. The message that no model is found indicates the the `PATH` for the command prompt that runs Jupyter does not have the OALIB installation in it.

**Comment by catauggie** [comment]
So, If I type PATH in command line, I have:
![bandicam 2022-12-23 16-14-11-606](https://user-images.githubusercontent.com/48176228/209342274-cd81cb8e-2b2a-4d19-8b28-71e8f0feba84.jpg)

if I type bellhop.exe, I have: "bellhop.exe" is not internal or external
command, executable program, or batch file.
![bandicam 2022-12-23 16-16-35-239](https://user-images.githubusercontent.com/48176228/209342363-1b86d48b-4a97-49be-af90-a7fd019042ee.jpg)

**Comment by catauggie** [comment]
maybe after adding bellhop.exe to PATH exist any extra actions to do?

**Comment by mchitre** [comment]
The text `bellhop.exe` should be removed from the PATH. The PATH is supposed to contain the directories, not the files.

**Comment by catauggie** [comment]
Yes, exactly this helped

**Comment by catauggie** [comment]
Thanks
