### ISSUE TITLE
arlpy outputs debug messages to stdout

### ISSUE THREAD

**Issue by vlaskine** [org-arl/arlpy#79]
Various arlpy methods output debug messages to stdout. It makes it impossible to use arlpy in the standard Linux pipeline mode like **cat some-input.csv | some-script-using-arlpy | process-output** ... It is quite a limitation and inconvenience. The fix is really straightforward.

The places I tripped over are (there may be other cases):

- using **print( something )**: should be **print( something, file=sys.stderr )** or **logging.info(...)** or alike.
- uwapm.py: **_proc.call(['bellhop.exe'] + list(args), stderr=_proc.STDOUT)** should be **stderr=_proc.STDERR**

**Comment by mchitre** [comment]
Fair enough. Would you be willing to PR the changes needed @vlaskine?

**Comment by vlaskine** [comment]
Thanks, I just created a pull request: https://github.com/org-arl/arlpy/pull/80

It fixes only uwapm, because that's the only part of uwapy that we are currently using and thus that's the only one that I could test.

**Comment by mchitre** [comment]
Fixed by #80
