### ISSUE TITLE
spyder not displaying figures (inline or otherwise) from arlpy.plot

### ISSUE THREAD

**Issue by ahmd-mahm** [org-arl/arlpy#8]
`arlpy.plot` is not outputting a figure, inline or otherwise, on spyder. No error is detected by the IPython console and associated functions run till completion. Snapshot of what happens is attached:

![image](https://user-images.githubusercontent.com/19687045/44318832-ff35ba80-a46a-11e8-83ff-9967e27c0dd5.png)

**Comment by mchitre** [comment]
Just tested in a plain IPython session on Mac OS X, works fine. I presume you're running on Windows?  I've not tried on Spyder, so may drop by your desk to explore what the problem is in person.

**Comment by mchitre** [comment]
Tested on Spyder on Windows. Issue seems to be that the Bokeh `output_notebook()` does not produce any output on Spyder, although it does in a IPython shell. Using `output_file()` instead works, but appends all outputs to a single file.
