### ISSUE TITLE
Ability to plot a transmission loss slice at one receiver depth

### ISSUE THREAD

**Issue by bbbrandyn** [org-arl/arlpy#86]
I was trying to implement in arlpy a way to plot a transmission loss slice at one receiver depth such as is done by the plottlr.m script in the Acoustics Toolbox. But I noticed that the values in each row of a `tloss` are complex numbers so I'm not sure how to simply plot the transmission loss at one depth. How can I use the data returned from `compute_transmission_loss()` in this way? This image is what I'm trying to accomplish for a selected receiver depth.
![image](https://github.com/org-arl/arlpy/assets/136633941/2f027af7-9f4a-42db-bbf3-87d7aaaac5d7)

**Comment by mchitre** [comment]
See #72 and #83 for a discussion on complex transmission loss. With #83, the transmission loss will be reported as real, with the phase compensated in the arrival time.

**Comment by mchitre** [comment]
Released v1.8.3, which should fix this.
