### ISSUE TITLE
why is max_angle (and min) limited in bellhop uwapm?

### ISSUE THREAD

**Issue by nlbeaird** [org-arl/arlpy#88]
Hi, this is a very useful package, thanks! Apologies if this isn't the place for this question. I'm fairly new to this, but I'm wondering why the `max_angle` and `min_angle` in setting the bellhope env file are limited to (-90, 90)? shouldn't one be able to have an omni directional source that ins't on the edge of a domain? Thanks for any insight

**Comment by mchitre** [comment]
This is a design choice made by the developer of BELLHOP (which `arlpy` simply wraps, and so has no opinion on). I believe the decision is reasonable for many scenarios – especially if there is no range dependence, due to the symmetry of the environment.
